proposed fix for https://trello.com/c/NKMvt2z9/17-bug-while-running-with-a-bzquery-composererror-expected-a-single-document-in-the-stream
strict yaml breaks easily , so first check if there is a bzaf
in the comment , then try to verify with strictyaml

ERROR:
ruamel.yaml.composer.ComposerError: expected a single document in the stream

tested to work :

(bzaf_venv) [r@r bzaf]$ bzaf --fatal --interactive-login --bugzilla https://partner-bugzilla.redhat.com --required-status ON_QA --verified-status VERIFIED --verified-resolution VERIFIED --bz-query='https://partner-bugzilla.redhat.com/buglist.cgi?bug_severity=unspecified&bug_severity=urgent&bug_severity=high&bug_status=ON_QA&classification=Red%20Hat&columnlist=bug_status%2Cshort_desc%2Cbug_id&f1=cf_internal_whiteboard&known_name=all%20ON_QA%20pidone&list_id=10116655&o1=substring&priority=unspecified&priority=urgent&priority=high&query_based_on=all%20ON_QA%20pidone&query_format=advanced&v1=DFG%3APIDONE'|& tee test.out
BZ ##1651357 ON_QA      - michele@redhat.com - [OSP8] HAproxy fails to start during undercloud installation because rabbitmq is already binding on port 5672 is valid
BZ ##1674070 ON_QA      - emacchi@redhat.com - [OSP14] unable to login galera in with root account after changing the mysql root password is valid
BZ ##1657374 ON_QA      - jeckersb@redhat.com - [OSP9] Newer erlang in OSP should Obsolete erlang-reltool is valid
BZ ##1647587 ON_QA      - jeckersb@redhat.com - [OSP8 UPDATES] RMQ fails to start after minor update and reboot is valid
BZ ##1654041 ON_QA      - jeckersb@redhat.com - [OSP8 UPDATES] RMQ fails to start after minor update and reboot is valid
BZ ##1618761 ON_QA      - michele@redhat.com - xinetd service for galera-mon is deployed without a bind address is valid
BZ ##1654042 ON_QA      - jeckersb@redhat.com - [OSP8 UPDATES] RMQ fails to start after minor update and reboot is valid
BZ ##1657375 ON_QA      - jeckersb@redhat.com - [OSP8] Newer erlang in OSP should Obsolete erlang-reltool is valid
BZ ##1680280 ON_QA      - emacchi@redhat.com - [OSP13] Pacemaker resource constraints cause API outage during maintenance is valid
BZ ##1647593 ON_QA      - jeckersb@redhat.com - [OSP8 UPDATES] RMQ fails to start after minor update and reboot is valid
BZ ##1659072 ON_QA      - oalbrigt@redhat.com - osp8 overcloud deployment fails with : epmd reports: node 'rabbit' not running at all is valid
Proceeding with the following valid BZs:
[<Bug #1651357 on https://partner-bugzilla.redhat.com/xmlrpc.cgi at 0x7f0e33d55e90>, <Bug #1674070 on https://partner-bugzilla.redhat.com/xmlrpc.cgi at 0x7f0e33d55710>, <Bug #1657374 on https://partner-bugzilla.redhat.com/xmlrpc.cgi at 0x7f0e33d55c10>, <Bug #1647587 on https://partner-bugzilla.redhat.com/xmlrpc.cgi at 0x7f0e33d55fd0>, <Bug #1654041 on https://partner-bugzilla.redhat.com/xmlrpc.cgi at 0x7f0e33d55c50>, <Bug #1618761 on https://partner-bugzilla.redhat.com/xmlrpc.cgi at 0x7f0e33d55bd0>, <Bug #1654042 on https://partner-bugzilla.redhat.com/xmlrpc.cgi at 0x7f0e33d55d10>, <Bug #1657375 on https://partner-bugzilla.redhat.com/xmlrpc.cgi at 0x7f0e33d55250>, <Bug #1680280 on https://partner-bugzilla.redhat.com/xmlrpc.cgi at 0x7f0e33d55d50>, <Bug #1647593 on https://partner-bugzilla.redhat.com/xmlrpc.cgi at 0x7f0e33d55a90>, <Bug #1659072 on https://partner-bugzilla.redhat.com/xmlrpc.cgi at 0x7f0e33d55750>]
*** SUMMARY     ***
Queried bugs: 11
Valid bugs: 11
Auto verified bugs: 0
*** SUMMARY END ***

Change-Id: I6e23f6bb2e276864967bede4c960fe554f3d03cf