Update patch set 1
Patch Set 1:

Hey Pini,

Could you please fix some of the linting issues:
tox -e flake8
flake8 installed: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support,configparser==3.7.4,entrypoints==0.3,enum34==1.1.6,flake8==3.7.8,functools32==3.2.3.post2,mccabe==0.6.1,pycodestyle==2.5.0,pyflakes==2.1.1,typing==3.7.4
flake8 run-test-pre: PYTHONHASHSEED='506279898'
flake8 run-test: commands[0] | flake8
./bzaf/cli.py:238:80: E501 line too long (82 > 79 characters)
./bzaf/cli.py:244:80: E501 line too long (80 > 79 characters)
./bzaf/cli.py:248:80: E501 line too long (82 > 79 characters)
./bzaf/api/validator.py:60:1: E302 expected 2 blank lines, found 1
./bzaf/api/validator.py:71:35: W291 trailing whitespace
./bzaf/api/validator.py:77:24: W291 trailing whitespace
./bzaf/api/validator.py:82:24: F841 local variable 'tmp_cmd' is assigned to but never used
./bzaf/api/validator.py:83:9: E271 multiple spaces after keyword
./bzaf/api/validator.py:84:24: F841 local variable 'tmp_playbook' is assigned to but never used
./bzaf/api/validator.py:98:1: E302 expected 2 blank lines, found 1
./bzaf/api/v1/executor.py:33:22: E225 missing whitespace around operator
./bzaf/api/v1/executor.py:36:17: E117 over-indented
./bzaf/api/v1/backends/ansible.py:20:1: E302 expected 2 blank lines, found 1
./bzaf/api/v1/backends/ansible.py:23:55: E231 missing whitespace after ','
./bzaf/api/v1/backends/ansible.py:23:80: E501 line too long (80 > 79 characters)
./bzaf/api/v1/backends/ansible.py:26:80: E501 line too long (92 > 79 characters)
./bzaf/api/v1/backends/ansible.py:31:16: W292 no newline at end of file
ERROR: InvocationError for command /Users/vkhitrin/Projects/Development/bzaf/.tox/flake8/bin/flake8 (exited with code 1)
__________________________________________________________________________________________________________________ summary __________________________________________________________________________________________________________________
ERROR:   flake8: commands failed

Patch-set: 1
Reviewer: Gerrit User 1016438 <1016438@d5d70762-12d0-45a1-890d-524b12d3f735>